apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: http
spec:
  protocol:
    http:
      discoveryEndpoint: http://discovery:9999
  capacity: 1
  brokerPodSpec:
    imagePullSecrets: # Container Registry secret
      - name: SECRET
    containers:
      - name: http-broker
        image: IMAGE
        resources:
          limits:
            "{{PLACEHOLDER}}": "1"
