apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: http-grpc-broker-rust
spec:
  protocol:
    http:
      discoveryEndpoint: http://discovery:9999
  capacity: 1
  brokerPodSpec:
    imagePullSecrets: # GitHub Container Registry secret
      - name: ghcr
    containers:
      - name: http-grpc-broker-rust
        image: ghcr.io/dazwilkin/http-grpc-broker-rust@sha256:a4a7494aef44b49bd08f371add41db917553391ea397c60e9b4d213545b94f4e
        args:
          - --grpc_endpoint=0.0.0.0:50051
        resources:
          limits:
            "{{PLACEHOLDER}}": "1"
  instanceServiceSpec:
    ports:
      - name: grpc
        port: 50051
        targetPort: 50051
  configurationServiceSpec:
    ports:
      - name: grpc
        port: 50051
        targetPort: 50051
