apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: http
spec:
  protocol:
    http:
      discoveryEndpoint: http://discovery:9999
  capacity: 1
  brokerPodSpec:
    imagePullSecrets: # Container Registry secret
      - name: [[REPLACE]]
    containers:
      - name: http-broker
        image: ghcr.io/dazwilkin/akri-http-broker@sha256:ae647dab0d686bafaaec4b1c7cc1fdb1d42fa68242c447ac72eac3db6ef62e7b
        resources:
          limits:
            "{{PLACEHOLDER}}": "1"
