{{- if .Values.debugEcho.configuration.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.debugEcho.configuration.name }}
spec:
  discoveryHandler: 
    name: debugEcho
    discoveryDetails: |+
      {{- if .Values.debugEcho.configuration.discoveryDetails.descriptions }}
      descriptions:
      {{- toYaml .Values.debugEcho.configuration.discoveryDetails.descriptions | nindent 6 }}
      {{- else }}
      descriptions: []
      {{- end }}
  {{- if or .Values.debugEcho.configuration.brokerPod.image.repository .Values.debugEcho.configuration.brokerJob.image.repository }}
  {{- /* Only add brokerSpec if a broker image is provided */}}
  brokerSpec:
    {{- if .Values.debugEcho.configuration.brokerPod.image.repository }}
    brokerPodSpec:
      containers:
      - name: {{ .Values.debugEcho.configuration.name }}-broker
        image: {{ printf "%s:%s" .Values.debugEcho.configuration.brokerPod.image.repository .Values.debugEcho.configuration.brokerPod.image.tag | quote }}
        {{- with .Values.debugEcho.configuration.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        resources:
          requests:
            {{`"{{PLACEHOLDER}}"`}} : "1"
            memory: {{ .Values.debugEcho.configuration.brokerPod.resources.memoryRequest }}
            cpu: {{ .Values.debugEcho.configuration.brokerPod.resources.cpuRequest }}
          limits:
            {{`"{{PLACEHOLDER}}"`}} : "1"
            memory: {{ .Values.debugEcho.configuration.brokerPod.resources.memoryLimit }}
            cpu: {{ .Values.debugEcho.configuration.brokerPod.resources.cpuLimit }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- else }}
    brokerJobSpec:
      template:
        spec:
          containers:
          - name: {{ .Values.debugEcho.configuration.name }}-broker
            image: {{ printf "%s:%s" .Values.debugEcho.configuration.brokerJob.image.repository .Values.debugEcho.configuration.brokerPod.image.tag | quote }}
            {{- if .Values.debugEcho.configuration.brokerJob.command }}
            command: 
              {{- toYaml .Values.debugEcho.configuration.brokerJob.command | nindent 14 }}
            {{- end }}
            {{- with .Values.debugEcho.configuration.pullPolicy }}
            imagePullPolicy: {{ . }}
            {{- end }}
            resources:
              requests:
                {{`"{{PLACEHOLDER}}"`}} : "1"
                memory: {{ .Values.debugEcho.configuration.brokerJob.resources.memoryRequest }}
                cpu: {{ .Values.debugEcho.configuration.brokerJob.resources.cpuRequest }}
              limits:
                {{`"{{PLACEHOLDER}}"`}} : "1"
                memory: {{ .Values.debugEcho.configuration.brokerJob.resources.memoryLimit }}
                cpu: {{ .Values.debugEcho.configuration.brokerJob.resources.cpuLimit }}
          restartPolicy: {{ .Values.debugEcho.configuration.brokerJob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      backoffLimit: {{ .Values.debugEcho.configuration.brokerJob.backoffLimit }}
      parallelism: {{ .Values.debugEcho.configuration.brokerJob.parallelism }}
      completions: {{ .Values.debugEcho.configuration.brokerJob.completions }}
    {{- end }}
  {{- end }}
  {{- if or .Values.debugEcho.configuration.brokerPod.image.repository .Values.debugEcho.configuration.brokerJob.image.repository }}
  {{- if .Values.debugEcho.configuration.createInstanceServices }}
  instanceServiceSpec:
    type: {{ .Values.debugEcho.configuration.instanceService.type }}
    ports:
    - name: {{ .Values.debugEcho.configuration.instanceService.name }}
      port: {{ .Values.debugEcho.configuration.instanceService.port }}
      protocol: {{ .Values.debugEcho.configuration.instanceService.protocol }}
      targetPort: {{ .Values.debugEcho.configuration.instanceService.targetPort }}
  {{- end }}
  {{- if .Values.debugEcho.configuration.createConfigurationService }}
  configurationServiceSpec:
    type: {{ .Values.debugEcho.configuration.configurationService.type }}
    ports:
    - name: {{ .Values.debugEcho.configuration.configurationService.name }}
      port: {{ .Values.debugEcho.configuration.configurationService.port }}
      protocol: {{ .Values.debugEcho.configuration.configurationService.protocol }}
      targetPort: {{ .Values.debugEcho.configuration.configurationService.port }}
  {{- end }}
  {{- end }}
  {{- if .Values.debugEcho.configuration.brokerProperties }}
  brokerProperties:
  {{- range $key, $val := .Values.debugEcho.configuration.brokerProperties }}
  {{- $key | nindent 4 }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  brokerProperties: {}
  {{- end }}
  capacity: {{ .Values.debugEcho.configuration.capacity }}
{{- end }}
