{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: akri-agent-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-agent
    release: prometheus
spec:
  selector:
    matchLabels: {{- include "akri.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: akri-agent
  podMetricsEndpoints:
  - port: {{ .Values.prometheus.portName | quote }}
    path: {{ .Values.prometheus.endpoint }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: akri-controller-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-controller
    release: prometheus
spec:
  selector:
    matchLabels: {{- include "akri.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: akri-controller
  podMetricsEndpoints:
  - port: {{ .Values.prometheus.portName | quote }}
    path: {{ .Values.prometheus.endpoint }}
{{- end }}