[package]
name = "coap-device"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coap = "0.11.0"
coap-lite = "0.5"
tokio = "1.8.1"
