# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opcua_node.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10opcua_node.proto\x12\tOpcuaNode\"\x0e\n\x0cValueRequest\"4\n\rValueResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x14\n\x0copcua_server\x18\x02 \x01(\t2J\n\tOpcuaNode\x12=\n\x08GetValue\x12\x17.OpcuaNode.ValueRequest\x1a\x18.OpcuaNode.ValueResponseB\x0c\xaa\x02\tOpcuaNodeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opcua_node_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\tOpcuaNode'
  _VALUEREQUEST._serialized_start=31
  _VALUEREQUEST._serialized_end=45
  _VALUERESPONSE._serialized_start=47
  _VALUERESPONSE._serialized_end=99
  _OPCUANODE._serialized_start=101
  _OPCUANODE._serialized_end=175
# @@protoc_insertion_point(module_scope)
