# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera.proto',
  package='camera',
  syntax='proto3',
  serialized_options=b'\252\002\006Camera',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x0f\n\rNotifyRequest\"/\n\x0eNotifyResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x0e\n\x06\x63\x61mera\x18\x02 \x01(\t2C\n\x06\x43\x61mera\x12\x39\n\x08GetFrame\x12\x15.camera.NotifyRequest\x1a\x16.camera.NotifyResponseB\t\xaa\x02\x06\x43\x61merab\x06proto3'
)




_NOTIFYREQUEST = _descriptor.Descriptor(
  name='NotifyRequest',
  full_name='camera.NotifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=39,
)


_NOTIFYRESPONSE = _descriptor.Descriptor(
  name='NotifyResponse',
  full_name='camera.NotifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='camera.NotifyResponse.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera', full_name='camera.NotifyResponse.camera', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['NotifyRequest'] = _NOTIFYREQUEST
DESCRIPTOR.message_types_by_name['NotifyResponse'] = _NOTIFYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotifyRequest = _reflection.GeneratedProtocolMessageType('NotifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYREQUEST,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.NotifyRequest)
  })
_sym_db.RegisterMessage(NotifyRequest)

NotifyResponse = _reflection.GeneratedProtocolMessageType('NotifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYRESPONSE,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.NotifyResponse)
  })
_sym_db.RegisterMessage(NotifyResponse)


DESCRIPTOR._options = None

_CAMERA = _descriptor.ServiceDescriptor(
  name='Camera',
  full_name='camera.Camera',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='camera.Camera.GetFrame',
    index=0,
    containing_service=None,
    input_type=_NOTIFYREQUEST,
    output_type=_NOTIFYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERA)

DESCRIPTOR.services_by_name['Camera'] = _CAMERA

# @@protoc_insertion_point(module_scope)
