# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x0f\n\rNotifyRequest\"/\n\x0eNotifyResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x0e\n\x06\x63\x61mera\x18\x02 \x01(\t2C\n\x06\x43\x61mera\x12\x39\n\x08GetFrame\x12\x15.camera.NotifyRequest\x1a\x16.camera.NotifyResponseB\t\xaa\x02\x06\x43\x61merab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\006Camera'
  _NOTIFYREQUEST._serialized_start=24
  _NOTIFYREQUEST._serialized_end=39
  _NOTIFYRESPONSE._serialized_start=41
  _NOTIFYRESPONSE._serialized_end=88
  _CAMERA._serialized_start=90
  _CAMERA._serialized_end=157
# @@protoc_insertion_point(module_scope)
