name: Build Agent

on:
  push:
    branches: [ main ]
    paths:
    - .github/actions/build-component-per-arch/**
    - .github/actions/build-component-multi-arch/**
    - .github/workflows/build-agent-container.yml
    - build/containers/Dockerfile.agent
    - agent/**
    - shared/**
    - build/setup.sh
    - version.txt
    - build/akri-containers.mk
    - Makefile
  pull_request_target:
    branches: [ main ]
    paths:
    - .github/actions/build-component-per-arch/**
    - .github/actions/build-component-multi-arch/**
    - .github/workflows/build-agent-container.yml
    - build/containers/Dockerfile.agent
    - agent/**
    - shared/**
    - build/setup.sh
    - version.txt
    - build/akri-containers.mk
    - Makefile
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/build-component-per-arch/**
    - .github/actions/build-component-multi-arch/**
    - .github/workflows/build-agent-container.yml
    - build/containers/Dockerfile.agent
    - agent/**
    - shared/**
    - build/setup.sh
    - version.txt
    - build/akri-containers.mk
    - Makefile
  release:
    types:
      - published

env:
  AKRI_COMPONENT: agent
  MAKEFILE_COMPONENT: agent

jobs:

  per-arch:
    # Run workflow pull_request if it is NOT a fork, as pull_request_target if it IS a fork
    if: >-
      ( github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork == true ) ||
      ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false ) ||
      ( !(startsWith(github.event_name, 'pull_request')) )
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        arch:
          - arm64v8
          - arm32v7
          - amd64

    steps:
    - name: Checkout the merged commit from PR and base branch
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request_target'
      with:
        # pull_request_target is run in the context of the base repository
        # of the pull request, so the default ref is master branch and
        # ref should be manually set to the head of the PR
        ref: refs/pull/${{ github.event.pull_request.number }}/head

    - name: Checkout the head commit of the branch
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Deps
      run: |
        yarn install
        yarn add @actions/core @actions/github @actions/exec fs

    - name: Run Per-Arch component build for ${{ env.AKRI_COMPONENT }}
      uses: ./.github/actions/build-component-per-arch
      with:
        github_event_name: ${{ github.event_name }}
        github_ref: ${{ github.ref }}
        github_event_action: ${{ github.event.action }}
        github_merged: ${{ github.event.pull_request.merged }}
        container_name: ${{ env.AKRI_COMPONENT }}
        container_prefix: ghcr.io/deislabs/akri
        container_registry_base_url: ghcr.io
        container_registry_username: ${{ secrets.crUsername }}
        container_registry_password: ${{ secrets.crPassword }}
        dockerhub_username: ${{ secrets.dhUsername }}
        dockerhub_password: ${{ secrets.dhPassword }}
        makefile_component_name: ${{ env.MAKEFILE_COMPONENT }}
        platform: ${{ matrix.arch }}
        build_rust: "1"

  multi-arch:
    if: (github.event_name == 'release') || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (startsWith(github.event_name, 'pull_request') && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref != 'refs/heads/main')
    needs: per-arch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Deps
      run: |
        yarn install
        yarn add @actions/core @actions/github @actions/exec fs

    - name: Run Multi-Arch component build for ${{ env.AKRI_COMPONENT }}
      uses: ./.github/actions/build-component-multi-arch
      with:
        github_event_name: ${{ github.event_name }}
        container_name: ${{ env.AKRI_COMPONENT }}
        container_prefix: ghcr.io/deislabs/akri
        container_registry_base_url: ghcr.io
        container_registry_username: ${{ secrets.crUsername }}
        container_registry_password: ${{ secrets.crPassword }}
        dockerhub_username: ${{ secrets.dhUsername }}
        dockerhub_password: ${{ secrets.dhPassword }}
        makefile_component_name: ${{ env.MAKEFILE_COMPONENT }}
