name: Build Webhook Configuration

on:
  push:
    branches:
      - main
      - "webhook-configuration"
    paths:
      - webhooks/validating/configuration/**
      - version.txt

env:
  AKRI_COMPONENT: webhook-configuration

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.crUsername }}
          password: ${{ secrets.crPassword }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            COMPONENT=${{ matrix.component }}
          context: .
          file: ./build/containers/Dockerfile.webhook-configuration
          tags: ghcr.io/deislabs/akri/${{ env.AKRI_COMPONENT }}:v1
